import numpy as np
import torch

import utils

from matplotlib import pyplot as plt

from .simulator import Simulator


class TwoMoonsSimulator(Simulator):
    """
    Implemenation of two moons simulator as described in section 4.1 and Appendix A.5.1 of
    'Automatic Posterior Transformation'.
    """

    def __init__(self):
        super().__init__()
        pass

    def simulate(self, parameters):
        """
        Generates observations for the given batch of parameters.

        :param parameters: torch.Tensor
            Batch of parameters.
        :return: torch.Tensor
            Batch of observations.
        """

        # Run simulator in NumPy.
        if isinstance(parameters, torch.Tensor):
            parameters = utils.tensor2numpy(parameters)

        # If we have a single parameter then view it as a batch of one.
        if parameters.ndim == 1:
            return self.simulate(parameters[None, ...])

        num_simulations = parameters.shape[0]

        # Keep track of total simulations.
        self.num_total_simulations += num_simulations

        # Run simulator.
        a = np.pi * np.random.rand(num_simulations) - np.pi / 2
        r = 0.01 * np.random.randn(num_simulations) + 0.1
        p = np.column_stack([r * np.cos(a) + 0.25, r * np.sin(a)])
        s = (1 / np.sqrt(2)) * np.column_stack(
            [
                -np.abs(parameters[:, 0] + parameters[:, 1]),
                (-parameters[:, 0] + parameters[:, 1]),
            ]
        )
        return torch.Tensor(p + s)

    @staticmethod
    def get_ground_truth_parameters():
        """
        Returns dummy ground truth parameters as none are specified in
        'Automatic Posterior Transformation.'

        :return: torch.Tensor [parameter_dim]
            Ground truth parameters used to generate an observation.
        """
        return torch.Tensor([0, 0])

    @staticmethod
    def get_ground_truth_observation():
        """
        Returns ground truth observation using same seed as 'Sequential Neural Likelihood'.

        :return: torch.Tensor [observation_dim]
            Ground truth observation generated by ground truth parameters.
        """
        return torch.Tensor([0, 0])

    def get_ground_truth(self):
        """
        :return: (torch.Tensor, torch.Tensor)
            Ground truth (parameter, observation) pair.
        """
        return self.get_ground_truth_parameters(), self.get_ground_truth_observation()

    @property
    def observation_dim(self):
        return 2

    @property
    def parameter_dim(self):
        return 2

    @property
    def name(self):
        return "two-moons"

    @property
    def parameter_plotting_limits(self):
        return [-2, 2]


def test_():
    simulator = TwoMoonsSimulator()
    num_parameters = 10000
    parameters = np.zeros((num_parameters, 2))
    observations = simulator.simulate(parameters)
    plt.scatter(observations[:, 0], observations[:, 1], s=1, alpha=0.1)
    plt.show()


def main():
    test_()


if __name__ == "__main__":
    main()
